## Version Selection for compose file
# https://docs.docker.com/compose/compose-file/#/versioning
version: '2'
services:
  es_v1:
    image: elasticsearch:1
    ports:
     - "9201:9200"
    volumes:
     - .:/apps
    entrypoint: /apps/docker-entrypoint-es1-plugins.sh
